### ISSUE TITLE
cf push fails

### ISSUE THREAD

**Issue by aboettger** [cloudfoundry-incubator/admin-ui#151]
```
cf push admin
```

says

```
2016-02-16T16:29:59.18+0100 [App/0]      ERR /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:32:in `read': No such file or directory @ rb_sysopen - config.ru (Errno::ENOENT)
2016-02-16T16:29:59.18+0100 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:32:in `load'
2016-02-16T16:29:59.18+0100 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
2016-02-16T16:29:59.18+0100 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
2016-02-16T16:29:59.18+0100 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
2016-02-16T16:29:59.18+0100 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
2016-02-16T16:29:59.18+0100 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
2016-02-16T16:29:59.18+0100 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/bin/thin:23:in `load'
2016-02-16T16:29:59.18+0100 [App/0]      ERR 	from /home/vcap/app/vendor/bundle/ruby/2.2.0/bin/thin:23:in `<main>'
2016-02-16T16:29:59.19+0100 [App/0]      OUT 
2016-02-16T16:29:59.22+0100 [DEA/0]      ERR Instance (index 0) failed to start accepting connections
```

**Comment by rboykin** [comment]
Check this issue:  https://github.com/cloudfoundry-incubator/admin-ui/issues/145  
Admin ui not really designed to be deployed as a cf app.  In fact, given it is monitoring cf, it is normally intentionally not deployed as a cf app.
